### ISSUE TITLE
switching to first person then back, terrain is still drawn

### ISSUE THREAD

**Issue by patrickdenglerhobbisoft** [patrickdenglerhobbisoft/WorldDefense#10]
I would have though removing the game object would do it, but it keeps drawing?
# if USETERRAIN

```
                _gameObjects.Objects.Remove(_gameObjects.Objects.OfType<RoadTerrainObject>().First());
```
# endif

**Comment by helmut-g** [comment]
@patrickdenglerhobbisoft The RoadTerrainObject did not remove the TerrainObject in OnUnload. I have added the proper OnUnload code. 
However, loading and unloading the terrain, roads and skies is expensive. I have added IsEnabled flags to the terrain and skies, which hides the graphics but does not unload them. The terrain and sky objects are now loaded only once and disabled in aerial view.

Please close this issue if the new solution is OK for you.

**Comment by patrickdenglerhobbisoft** [comment]
no longer an issue. Fix is great!
