### ISSUE TITLE
disappearing encountering turns on white house

### ISSUE THREAD

**Issue by Xerenn** [patrickdenglerhobbisoft/WorldDefense#108]
cars vanish on some turns

**Comment by patrickdenglerhobbisoft** [comment]
my suspicion here is that either they are running into the phone booth (which I haven't written the code to show that damage) or they are getting killed by a tower that is also not showing damage.

**Comment by patrickdenglerhobbisoft** [comment]
Ok, I removed the phone booth from the physics model, and they should now explode a bit too. Fixed in next release.
