### ISSUE TITLE
Returning to main menu

### ISSUE THREAD

**Issue by HiGuyz1** [patrickdenglerhobbisoft/WorldDefense#110]
After waiting through the title screen I hit new game, then backed out of the location picker. When I returned to the main screen I was given a black screen with none of the options -New, continue etc.- on the TV, but the background remained and the TV was still there. The screenshot became glitched as well.
![2015-12-30_00001](https://cloud.githubusercontent.com/assets/16470496/12047968/36cc90f2-ae89-11e5-821d-f7c209d6d22c.jpg)

**Comment by patrickdenglerhobbisoft** [comment]
Ug, tricky onel.  Fixed in next build:
   private void btnExit_Click(object sender, RoutedEventArgs e)
        {
            this.Visibility = Visibility.Collapsed;
            ((this.Parent as System.Windows.Controls.Grid).Parent as StartScreen).ShowGridAgain();
        }

**Comment by HiGuyz1** [comment]
Nope
![2015-12-30_00004](https://cloud.githubusercontent.com/assets/16470496/12062396/bca8848e-af50-11e5-8835-afa0709d14d9.jpg)
![2015-12-30_00005](https://cloud.githubusercontent.com/assets/16470496/12062398/c018bd64-af50-11e5-95c5-9b3ea5987759.jpg)

(On these next two I compared something, I tried taking one before hovering over the options and one after)
Before:
![2015-12-30_00006](https://cloud.githubusercontent.com/assets/16470496/12062401/d52f0d66-af50-11e5-906c-b5ccf8ca1da6.jpg)
After:
![2015-12-30_00007](https://cloud.githubusercontent.com/assets/16470496/12062404/d88ea53e-af50-11e5-8168-190e7d2df7ea.jpg)

**Comment by HiGuyz1** [comment]
Woops
I got this one mixed up with the screen shots one
Returnign to menu is fixed but now when hovering over one of the options I see the highlight for the defend button that is distorted.

**Comment by patrickdenglerhobbisoft** [comment]
This was redone recheck
