### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by HiGuyz1** [patrickdenglerhobbisoft/WorldDefense#111]
Taking screenshots is busted. In both of these I had alt-tabbed and clicked back into the game after.
![2015-12-30_00002](https://cloud.githubusercontent.com/assets/16470496/12047990/a78afea0-ae89-11e5-9e22-0c085896834b.jpg)
![2015-12-30_00001](https://cloud.githubusercontent.com/assets/16470496/12047991/a8c18226-ae89-11e5-8e64-40850bc21217.jpg)

**Comment by patrickdenglerhobbisoft** [comment]
I think I have to punt this.
