### ISSUE TITLE
Mashing begin communication

### ISSUE THREAD

**Issue by HiGuyz1** [patrickdenglerhobbisoft/WorldDefense#112]
I clicked Begin Communication several times after putting two towers down and the com tower:
Sound (I think the flame thrower sound) kept going for a second, and is still looping
Massive lag and slow down
Two cars bumped into another truck, the truck exploded (Don't have this happen!)
All cars destroyed, game says there is still one remaining
Wave 1 box stayed on the screen
No money collected
A good fix would be to disable begin communication during the round.

**Comment by HiGuyz1** [comment]
In the same instance I tried to upgrade my turrets:
When I upgraded one the affect went to both of them.
Cash went below zero.

**Comment by patrickdenglerhobbisoft** [comment]
Ok, you'll probably get away with a little mashing, but in the next build, I hide to towers bit after you click begin communciations, and I'm disabling the button afterwrards too.  Do make sure that the button comes back alive though between rounds.

**Comment by HiGuyz1** [comment]
I don't think it came back alive at all.

**Comment by HiGuyz1** [comment]
When starting wave one, I accidentally kept clicking it, as seen in this image, even though the wave had started, the box was stuck in the middle of the screen.
![wave box stuck](https://cloud.githubusercontent.com/assets/16470496/12070979/e6e8eb6a-b047-11e5-89c9-04ae39ed3d76.png)

**Comment by patrickdenglerhobbisoft** [comment]
I'm gonna let you fire off as many rounds as you want as often as you want.
