### ISSUE TITLE
Cars don't know where to go

### ISSUE THREAD

**Issue by HiGuyz1** [patrickdenglerhobbisoft/WorldDefense#113]
Simple as that, I watched two cars go around in circles on wave one, location was white house on a real street.

**Comment by HiGuyz1** [comment]
Cars in general drive oddly, they don't seem to want to follow the road and are even too big for most of them. I would size them down, and have them not try to follow the road on a physical plain, this makes it hard for them to turn and might cause the looping affect.

**Comment by patrickdenglerhobbisoft** [comment]
Can you tell me exactly which map you are using?   I had a feature in there where some monters try to attack towers; I'm removing that. So retest on next buld.

**Comment by HiGuyz1** [comment]
I have been using the whitehouse as a standard to keep a little consistancy, but I have also been using some movement in the area, like off streets and on them.
However this is still an issue in the current build
![car frame 1](https://cloud.githubusercontent.com/assets/16470496/12070897/cfc5e7d8-b044-11e5-9b4c-5e85a95fbf9c.png)
![car frame 2](https://cloud.githubusercontent.com/assets/16470496/12070900/d93dce7a-b044-11e5-8e6e-62eab37a1ed3.png)
![car frame 3](https://cloud.githubusercontent.com/assets/16470496/12070901/d94bfbf8-b044-11e5-9cbc-3ac75db3a852.png)

**Comment by patrickdenglerhobbisoft** [comment]
Should be fixed (and is this a dupe?)
