### ISSUE TITLE
Scrolling map initiates blur

### ISSUE THREAD

**Issue by HiGuyz1** [patrickdenglerhobbisoft/WorldDefense#114]
I zoomed in and out several times, this causes screen jumping and glitching. Zooming in doesn't zoom 100% all the time, then zooming out when it won't zoom much causes it to quickly jump forward then jump back

**Comment by patrickdenglerhobbisoft** [comment]
Ok, this will be a challenge.  Let's try to get super specific.
1. I start with the default map zoom.
2. I zoom in quickly with the mouse button and (this unexpected thing happens).

Sorry, it's really hard to debug this stuff :)

**Comment by HiGuyz1** [comment]
Alright so now with the new blurring affect whenever I am zoomed out as far as you allow, and I scroll down, as if I were zooming out, it still blurs.

**Comment by patrickdenglerhobbisoft** [comment]
yes, rats...

**Comment by patrickdenglerhobbisoft** [comment]
gonna have to deal with this.
