### ISSUE TITLE
Sidebar

### ISSUE THREAD

**Issue by HiGuyz1** [patrickdenglerhobbisoft/WorldDefense#118]
Instead of making just the Begin Communications button disappear, you made the whole sidebar do it. This reveals the Bing logo!
I should have access to the towers during the round, don't take that away!

**Comment by Screamerclauz** [comment]
leave comment

**Comment by patrickdenglerhobbisoft** [comment]
I've decided for the time being to go with "towers are always available" so the side bar should not disappear..  If this is fixed close.

**Comment by HiGuyz1** [comment]
Did we already discuss this in person?
Also to explain me and Drake assigning eachother I was showing him that function.

**Comment by patrickdenglerhobbisoft** [comment]
i'm leaving tower control panel on all the time. fixed
