### ISSUE TITLE
Upgrades

### ISSUE THREAD

**Issue by HiGuyz1** [patrickdenglerhobbisoft/WorldDefense#119]
The cancel button is still assigned to give the upgrades, hitting upgrades with the needed money causes it to close instead.

**Comment by patrickdenglerhobbisoft** [comment]
I completely rewrote tower upgrade.  Please see if you are happy with it. If so, close this bug.

**Comment by HiGuyz1** [comment]
I like it, but eventually there should be a limit, I mentioned this in a later post. However you could set it back to a smaller size for its final form, but keep it at max range AND make it look different and cooler!

**Comment by patrickdenglerhobbisoft** [comment]
limited to level 5 and cancel now works
