### ISSUE TITLE
Endless

### ISSUE THREAD

**Issue by HiGuyz1** [patrickdenglerhobbisoft/WorldDefense#121]
In my build the round is seemingly endless
![endless](https://cloud.githubusercontent.com/assets/16470496/12062722/cef562c8-af56-11e5-8a9e-8a189803917a.png)
I don't see enough cars as the enemy counter is saying there are.

**Comment by patrickdenglerhobbisoft** [comment]
this was demo mode. I hope; please recheck

**Comment by HiGuyz1** [comment]
Seems to be all good in the neighborhood of the current build.
