### ISSUE TITLE
Wave I Complete But Stuck?

### ISSUE THREAD

**Issue by Tryxie1** [patrickdenglerhobbisoft/WorldDefense#124]
I completed Wave I successfully, but not sure what to do next. Begin Communications button is flashing red, but unable to proceed.

**Comment by patrickdenglerhobbisoft** [comment]
Ok, I fixed this. I disabled "begin communcations" so you didn't accidentally keep pressing it, but then I forgot to re-enable it.  I'm pushing a new RC5. Please make sure it works :)
