### ISSUE TITLE
Make Settings screen look good

### ISSUE THREAD

**Issue by patrickdenglerhobbisoft** [patrickdenglerhobbisoft/WorldDefense#125]
I introduced a settings panel but have not made it look like the rest.  Please refine this control.

**Comment by christopherdude** [comment]
Changed to temp look with green msgbox... waiting on Pat decision for final look n' feel for all controls before keeping this permanant

**Comment by patrickdenglerhobbisoft** [comment]
Skype message : keep the metallic :)

**Comment by patrickdenglerhobbisoft** [comment]
I put the metallic in
