### ISSUE TITLE
tower upgrade and size

### ISSUE THREAD

**Issue by SliderUA** [patrickdenglerhobbisoft/WorldDefense#127]
the size of model increasing with each upgrade to much i think, and when aiming top of tower have a wrong position
![bug](https://cloud.githubusercontent.com/assets/16507489/12070327/a12b6ba6-b075-11e5-8ee2-ac0df4b81477.png)

**Comment by patrickdenglerhobbisoft** [comment]
I've reduced the over all size of the upgrade; I am still having some issues with towers, so I am leaving this open.

**Comment by patrickdenglerhobbisoft** [comment]
fixed.  upgrade clamped and size reasoable
