### ISSUE TITLE
Upgrade cost

### ISSUE THREAD

**Issue by HiGuyz1** [patrickdenglerhobbisoft/WorldDefense#129]
When upgrading a tower:
The cost per upgrade raises, but I cannot see it change on the upgrade button.
There is no limit to the upgrades so tower can become impossibly big and not able to be clicked on again, also this causes the camera to clip into the tower.

**Comment by HiGuyz1** [comment]
This also means the tower can kill and enemy from anywhere and not be affected by physics!

**Comment by patrickdenglerhobbisoft** [comment]
Fixed the cost upgrade issue.
Also clamped level at 5 (please test)
And I made towers grow less.
