### ISSUE TITLE
Announcing waves

### ISSUE THREAD

**Issue by HiGuyz1** [patrickdenglerhobbisoft/WorldDefense#139]
When announcing a wave, there should not be a large box as there is now, just either one big enough for all the text or no background at all.

**Comment by patrickdenglerhobbisoft** [comment]
I like the no border/background. done.

**Comment by christopherdude** [comment]
ACK!  Which one?!?

**Comment by patrickdenglerhobbisoft** [comment]
One you haven’t worked on I hope?  RoundControlSimple?
