### ISSUE TITLE
Add map constraints so user cannot move too far out of range of game

### ISSUE THREAD

**Issue by patrickdenglerhobbisoft** [patrickdenglerhobbisoft/WorldDefense#15]

**Comment by patrickdenglerhobbisoft** [comment]
make it so the user cannot scroll too far off the screen (left/right/up/down)  zoom in and out is already constrained.

**Comment by christopherdude** [comment]
I'm currently working on this one

**Comment by christopherdude** [comment]
This was edited and I left notes in email regarding this.
