### ISSUE TITLE
before drop tower - project selection ring onto map instead of at tower to show *real* range to user

### ISSUE THREAD

**Issue by patrickdenglerhobbisoft** [patrickdenglerhobbisoft/WorldDefense#16]

**Comment by helmut-g** [comment]
@patrickdenglerhobbisoft Ring is now rendered using a billboard which is always clamped to the ground (y = 0). Please check the new implementation and close this issue if the solution is OK for you.

**Comment by patrickdenglerhobbisoft** [comment]
this is working well.
