### ISSUE TITLE
Selector circles should draw under models and should not draw in any mode but arial

### ISSUE THREAD

**Issue by patrickdenglerhobbisoft** [patrickdenglerhobbisoft/WorldDefense#2]

**Comment by patrickdenglerhobbisoft** [comment]
Thought I did this but I guess not

**Comment by helmut-g** [comment]
@patrickdenglerhobbisoft Ring is now rendered using a billboard which is always clamped to the ground (y = 0). This makes it draw under the models and under the smoke effect.
In first-person view the billboard is disabled. 
Please check the new implementation and close this issue if the solution is OK for you.

**Comment by patrickdenglerhobbisoft** [comment]
This is great; in fact i disabled all rings except selected.
