### ISSUE TITLE
Improve code structure

### ISSUE THREAD

**Issue by helmut-g** [patrickdenglerhobbisoft/WorldDefense#27]
The current code structure is a bit confusing, e.g. game objects are created in various place: Some are created in MainGame, some in GameController, some in other GameObjects.

I recommend to structure the code like this:
The MainGame creates services/managers. In general no game objects.
The GameController creates the general game objects for the level, e.g. terrain, sky, lights, ...
The GameObjects should contain only game logic for their own topic, e.g. the camera objects should not be responsible for terrain creation - this is very unexpected for me.

**Comment by patrickdenglerhobbisoft** [comment]
We’re colliding; get latest )

https://github.com/patrickdenglerhobbisoft/WorldDefense/issues/28

and look at that one when you’re ready.

**Comment by helmut-g** [comment]
Some concrete changes I would make:
Move creation of sky objects from MainGame to GameController.
Move creation of terrain object from CamerObject to GameController.

**Comment by helmut-g** [comment]
Please also use _ prefix (e.g. `_scene`) for fields and no prefix for local variables (e.g. `scene`). In the current code some local variables use _ which makes it more difficult for me to understand and change the code.

**Comment by helmut-g** [comment]
Also it would help me if fields are defined in one block at the beginning of the class and not scattered between methods.

**Comment by helmut-g** [comment]
Currently, it is difficult to test aspects of the game in isolation. For example: If I want to work on the attached particle effects for the monsters, it would be nice to have a game level/mode, where a monster is driving in circles and I can check the attached effects. Not sure if this is possible with the current code architecture...

**Comment by patrickdenglerhobbisoft** [comment]
punting (unfortunately) to v2 for now
