### ISSUE TITLE
Polyline not drawing

### ISSUE THREAD

**Issue by patrickdenglerhobbisoft** [patrickdenglerhobbisoft/WorldDefense#28]
GET LATEST :)  We were colliding, but I am going to bed:  If you can sneak this back into monster then figure out why the polylines weren't drawing that'd be cool :)

if (_monsterDefintion.UniqueMonsterBehavior == ContentController.UniqueMonsterBehaviorEnum.Dummy)
                {
                    // TODO: HELMUT Why is my polyline not drawing :(
                    if ((this.gameObjectName == "Home") && (Statics.GameState.CurrentGameState == GameState.GameStateEnum.NewGameBeforeDrop))
                    {
                        this.CurrentGeoLoc = _locationManager.ConvertToGeoCoordinate(this.RigidBody.Pose.Position);
                        Statics.GameFinalTargetGeoLoc = new GeoCoordinate(this.CurrentGeoLoc.Latitude, this.CurrentGeoLoc.Longitude);
                        // move tutorial along
                        Statics.MessageQueue.Enqueue(new string[] { "MESSAGEBOX_CLOSED" });
                        Statics.MessageQueue.Enqueue(new string[] { "MESSAGEBOX", "", "Tutorial", "Now drag and drop some towers from the control panel to the map.  Position these towers such that they will destroy incoming enemies before they reach your phone booth.", "TUTORIALF2" });
                        Statics.GameState.CurrentGameState = GameState.GameStateEnum.NewGameHomePlaced;
                        GameController.AddMonster("Dummy");
                    }
                }

**Comment by helmut-g** [comment]
@patrickdenglerhobbisoft I need more info for this issue. I am not sure where the code above fits in.
