### ISSUE TITLE
show enemy path on areial map and create roads for path

### ISSUE THREAD

**Issue by patrickdenglerhobbisoft** [patrickdenglerhobbisoft/WorldDefense#29]
I think I mostly have this, however, I'm did in a horribly inneficient way.  So then I backed it out;
I'm not sure how to build a path with multiple start / stop points, but as you will see, I call CreateAvailableRoutes() with 4 different paths.  

The current code builds one path  (from two of the four sources -> by reversing one so one goes in and one goes out).

What I want is of course to build their paths in terrain mode, but first and foremost, I want to show simple path drawing on the map (via DigitalRune).

**Comment by helmut-g** [comment]
Some notes: 
The road of the TerrainRoadLayer was not designed for very tight curves. The road will look strange if the curves are too tight. Is this a problem?

The lines of the DebugRenderer always have a thickness of 1. In DR you can use figures (http://www.digitalrune.com/Documentation/html/d70873e7-1dbc-492b-b10d-1afb6f06687a.htm) to draw lines with a thickness. I have added a path figure in RoadTerrainObject.

**Comment by helmut-g** [comment]
The path is now rendered like this:
![image](https://cloud.githubusercontent.com/assets/3626369/11918958/00d05764-a744-11e5-8182-608dd17cd2a8.png)

If it should have arrows, we need a more complicated solution.

**Comment by helmut-g** [comment]
If you need a road/path with multiple start/stop points, I would create multiple roads/paths.

**Comment by patrickdenglerhobbisoft** [comment]
punting to v2
