### ISSUE TITLE
Clean up Tower Upgrade XAML

### ISSUE THREAD

**Issue by patrickdenglerhobbisoft** [patrickdenglerhobbisoft/WorldDefense#30]
Don't worry about functionality, but do make sure it doesn't look "like XAML" if you can.   

I think that may mean that the background.png isn't so rectangular?  

Also, I hate the color on the title (same as on Messagebox.xaml); i'd love to have some sort of _reasonable_ gradient color animation on the title for example.

**Comment by christopherdude** [comment]
Please see email for sample of new msgbox sent 12/24 in the afternoon

**Comment by patrickdenglerhobbisoft** [comment]
I'm closing this for now; but hold onto the files.  I need to freeze the UI in favor of other features.
