### ISSUE TITLE
Style butttons

### ISSUE THREAD

**Issue by patrickdenglerhobbisoft** [patrickdenglerhobbisoft/WorldDefense#31]
Style the buttons on the title screen to look like this 
![likethisone](https://cloud.githubusercontent.com/assets/7421014/11916810/6f566b58-a69d-11e5-8775-7b5c1866f961.png)

Take the rest of the buttons, and use this as a template: only make green (good) red (bad/cancel)

![button05](https://cloud.githubusercontent.com/assets/7421014/11916819/03350410-a69e-11e5-9811-f06d8446468d.png)

AND, trim the edges so they follow the internal design just like this (though I just chopped it and it's missing the nice edges)
![button5edged](https://cloud.githubusercontent.com/assets/7421014/11916825/20818426-a69e-11e5-82b1-7aaad0b699b3.png)

**Comment by christopherdude** [comment]
YO - I have the MIB menu thing lookin' closer.  Please don't edit the style, but rather indicate desired changes in here.  Also, I need the PSD file for the red button you have above.  If you do not have said PSD file (Photoshop file) let me know if you have anything else other than just this png

**Comment by christopherdude** [comment]
I think you're misunderstanding.  I don't need the PNG file.  I need the PSD file.  This is the source file for use in photoshop so I can put this button in appropriately.

**Comment by patrickdenglerhobbisoft** [comment]
I'm super happy with the buttons.  I'm closing

**Comment by patrickdenglerhobbisoft** [comment]
I’m super happy with the buttons now; I thought you were talking about the panel.
