### ISSUE TITLE
Towers don't seem to fire when they should

### ISSUE THREAD

**Issue by patrickdenglerhobbisoft** [patrickdenglerhobbisoft/WorldDefense#35]
I'm not sure if this problem is within the firing logic or the range object; but some towers just don't seem to fire for a while.
1. start app
   2 drop projectile tower
2. start communications

notice that cars can actually run over the tower long before it fires; firing seems _almost_ random

**Comment by helmut-g** [comment]
To debug this I visualized the tower position and range and the monster position in TowerContentObject.CheckTarget:

```
private void CheckTarget(MonsterContentObject m)
{
    //_isFiring = (m == null && _debugTargetObject.IsTargetEnabled) ||
    //            (m != null && _locationManager.DistanceBetweenGeoCoordinatesIsClose(this.CurrentGeoLoc, m.CurrentGeoLoc, ComputeRange()));
    float rangeOffset = 1f;
    _isFiring = (m != null && _locationManager.DistanceBetweenGeoCoordinatesIsClose(this.CurrentGeoLoc, m.CurrentGeoLoc, ComputeRange()* rangeOffset));

    _debugRenderer.DrawBox(2 * ComputeRange(), 1, 2 * ComputeRange(), new Pose(_locationManager.ConvertToWorldSpace(CurrentGeoLoc)), Color.Violet, false, false);
    if (m != null)
        _debugRenderer.DrawBox(1, 1, 1, new Pose(_locationManager.ConvertToWorldSpace(m.CurrentGeoLoc)), Color.Red, false, false);

    if (!_isFiring)
        return;
```

(This code is not checked in.)

This showed that the monster geo location is ok. But the geo location of the tower is wrong. 
TowerContentObject.CurrentGeoLoc was not updated. I have added
`CurrentGeoLoc = _locationManager.ConvertToGeoCoordinate(RigidBody.Pose.Position);`
to TowerContentObject.OnUpdate. (Code checked in.)

The range computed by ComputeRange() was also different from the range used by the ring indicator: The ring used the property TowerContentObject.Range. ComputeRange() computes a range from _towerDefeintion.Range.
I have checked in code which updates TowerContentObject.Range.

Another issue that might be confusing was that the method `DistanceBetweenGeoCoordinatesIsClose` checked the x and z difference separately. That means the area covered by the tower was a square and not a circle. I have fixed the method.

**Comment by patrickdenglerhobbisoft** [comment]
This seems to be working though?  At least way better.

**Comment by patrickdenglerhobbisoft** [comment]
This seems to work very well now.
