### ISSUE TITLE
"default" or "next button to push" buttons should animate with colors

### ISSUE THREAD

**Issue by patrickdenglerhobbisoft** [patrickdenglerhobbisoft/WorldDefense#38]
Some sort of soft animation to the color or opacity (not much if you choose opacity) should happen on buttons like "Defend" and "Begin Communcations" to help the user find the next button to push.

**Comment by christopherdude** [comment]
For buttons, now do this when you want to "encourage" them to click a certain button:

```
        VisualStateManager.GoToState(btnStartRound, "Encouraged", true);
```

I put this in on line 53 on the control panel for you to see the "begin communications" light up in encouragement.  If you want me to change how that animation goes, describe the animation and I'll do it.  But right now it sort of flashes a little reddish.
