### ISSUE TITLE
Show some sort of hoverover effect on towers and help me align the images so they are uniform

### ISSUE THREAD

**Issue by patrickdenglerhobbisoft** [patrickdenglerhobbisoft/WorldDefense#39]
First, each of the images are offset just a little bit differently, so when you look at the panel of towers, they are jagged.  Change the individual image files such that they are reasonable centered/aligned when placed in the panel.

Also, add some sort of hover over grow/shrink effect to the tower icons.

**Comment by christopherdude** [comment]
This is done, I believe the icons are even, and we have grow/shrink in app.xaml style for this. Plus I added a little BLIP sound when they hover.

**Comment by christopherdude** [comment]
You didn't leave a comment?  What's wrong with these? 

CORRECTION: Never mind, I see that it's still assigned to you

**Comment by patrickdenglerhobbisoft** [comment]
No, this is all good now :)
