### ISSUE TITLE
Tower Upgrade Control needs finesse

### ISSUE THREAD

**Issue by patrickdenglerhobbisoft** [patrickdenglerhobbisoft/WorldDefense#40]
When you click on a tower, the tower upgrade control shows (needs fade too); but the text falls outside the boundaries for some reason.

**Comment by christopherdude** [comment]
I'm not seeing the text falling outside?  Attaching a screenshot, maybe you can tell me where?  Also, I no like these windows.  But each time I change them, they get changed back.  Is this the look you want to go for or can I change them to those new green ones?
![capture](https://cloud.githubusercontent.com/assets/9539359/12007954/b2df925e-abda-11e5-8ecf-8a0b85923fd8.JPG)

**Comment by patrickdenglerhobbisoft** [comment]
I feel like I've done the right stuff here.  Closing
