### ISSUE TITLE
Selecting Location

### ISSUE THREAD

**Issue by HiGuyz1** [patrickdenglerhobbisoft/WorldDefense#48]
When selecting a location, make it so the background is only covering the TV not the whole screen, otherwise it feels weird to have the TV at all.

**Comment by HiGuyz1** [comment]
Actually going anywhere now shows the same white screen

**Comment by patrickdenglerhobbisoft** [comment]
Need better detail here.

**Comment by HiGuyz1** [comment]
Re-stated in a later post by me with how to reproduce.
