### ISSUE TITLE
Towers don't touch ground

### ISSUE THREAD

**Issue by HiGuyz1** [patrickdenglerhobbisoft/WorldDefense#61]
Simple as before only not just affecting the 'white room'

**Comment by patrickdenglerhobbisoft** [comment]
Need more information on this.  Are you talking about in First Person view?  or are you expecting something that is not happening?

**Comment by HiGuyz1** [comment]
Did I already talk to you about this?

**Comment by HiGuyz1** [comment]
Not in first person view during this. I was expecting they'd hit the ground.

**Comment by HiGuyz1** [comment]
I believe this issue was fixed.
