### ISSUE TITLE
Returning to location

### ISSUE THREAD

**Issue by HiGuyz1** [patrickdenglerhobbisoft/WorldDefense#63]
When I zoom out of the map I want to return to where I am, include a button that can put me back there.

**Comment by patrickdenglerhobbisoft** [comment]
You shouldn't have been able to zoom out too far to begin with.  For some reason this code was disabled.  I've re-enabled it.   So, hopefully this is now a non-issue in that you cannot zoom out too far that you get lost.

**Comment by HiGuyz1** [comment]
You should also put an arrow to direct you back home if you move away from the comm tower on your screen.

**Comment by patrickdenglerhobbisoft** [comment]
See if you are happy with zoom not letting you zoom out too far

**Comment by HiGuyz1** [comment]
I am
