### ISSUE TITLE
Placing a tower

### ISSUE THREAD

**Issue by HiGuyz1** [patrickdenglerhobbisoft/WorldDefense#65]
When placing a tower I should click it once in the menu then click where I want to put it, clicking and holding is awkward because I accidentally will spawn it instead of moving it first.
The sound of placing a turret is off, it lands first then the sound plays.
Turret range is too low, it should simply surround it

**Comment by patrickdenglerhobbisoft** [comment]
I'm moving this to a nice to have; I really get it, and I've tried a few implementations that have failed.
