### ISSUE TITLE
Placing the comm tower

### ISSUE THREAD

**Issue by HiGuyz1** [patrickdenglerhobbisoft/WorldDefense#66]
When placing the comm tower I should be able to simply place it some where, when I am moving the mouse around and drop it, it should not slide around like on an ice rink.
I should be able to confirm the location of it, and when playing a pre-selected area it should already be set.

**Comment by patrickdenglerhobbisoft** [comment]
I think what you are saying is disable the map scroll left and right for the home tower; how important is this?

**Comment by HiGuyz1** [comment]
Don't disable map scroll, disable physics on the comm tower, placing it is difficult because when I put it down in this instance, the tower instead slipped far from where I wanted it to be.

**Comment by patrickdenglerhobbisoft** [comment]
need more info.  try again to see if it is still an issue
