### ISSUE TITLE
I should know where the enemies will go, start from and see their off road path, that way I can plan around it.

### ISSUE THREAD

**Issue by HiGuyz1** [patrickdenglerhobbisoft/WorldDefense#69]

**Comment by patrickdenglerhobbisoft** [comment]
I'm going to turn that feature on;  tell me if it helps, or if it hurts.  It's not great.  it shows too much; if you like the idea in general though, assign it back to me saying you like it.

**Comment by Xerenn** [comment]
eh..might be a good idea for easy/hard mode...personally i think the randomness of which roads they will take is part of the learning curve/fun no?

**Comment by HiGuyz1** [comment]
The randomness is fine, but I should be able to provide defenses against it before the round begins.

**Comment by patrickdenglerhobbisoft** [comment]
still debating

**Comment by patrickdenglerhobbisoft** [comment]
punting to V2
