### ISSUE TITLE
Shooting

### ISSUE THREAD

**Issue by HiGuyz1** [patrickdenglerhobbisoft/WorldDefense#78]
When the towers shoot they should aim at the enemy.

**Comment by patrickdenglerhobbisoft** [comment]
Need more information;  which towers are not aiming at the enemy?  (steps to reproduce again :))

**Comment by HiGuyz1** [comment]
At the time there was only the gun tower available, just in general the model should be looking at the enemies.

**Comment by HiGuyz1** [comment]
Gun tower definitely does not look over at enemies

**Comment by patrickdenglerhobbisoft** [comment]
fixed
