### ISSUE TITLE
Tutorial box

### ISSUE THREAD

**Issue by HiGuyz1** [patrickdenglerhobbisoft/WorldDefense#79]
The tutorial box won't disappear, and takes up a lot of the screen. I should be able to exit out of it, replay tutorials and opt out of the tutorials.

**Comment by patrickdenglerhobbisoft** [comment]
I agree; for now, did it just not disappear at all? Or did it not disappear until you did what it said.

If it did not disappear at all, give me steps to reproduce
1. start game
2. drop phone booth (whatever)

**Comment by HiGuyz1** [comment]
I got through wave 2 and it wouldn't disappear. The transmission had ended and it wouldn't leave the screen after it said transmission ended.
