### ISSUE TITLE
Tower bottoms

### ISSUE THREAD

**Issue by HiGuyz1** [patrickdenglerhobbisoft/WorldDefense#80]
The bottom of a tower is invisible, since they can be flipped over they should have a fill.

**Comment by patrickdenglerhobbisoft** [comment]
I need more information on this.  Send me a screenshot

**Comment by HiGuyz1** [comment]
![tower bottom](https://cloud.githubusercontent.com/assets/16470496/12070887/43df97dc-b044-11e5-9989-9b3732b0df08.png)

This also is apparent with cars
![undercar](https://cloud.githubusercontent.com/assets/16470496/12070890/4ebd27a0-b044-11e5-97c3-f995807c6215.png)

**Comment by patrickdenglerhobbisoft** [comment]
gonna have to deal with this though some are fixed
