### ISSUE TITLE
Tower health

### ISSUE THREAD

**Issue by Xerenn** [patrickdenglerhobbisoft/WorldDefense#87]
Youve got some super thin health bars for towers. also they are ugly. make them fatter so they will be clearer to read. Align them vertically to the left of the tower image instead of horizontally across the top. we wanna see the pretty tower. also in tower description/upgrade window, put tower health current/max in numerical form. Tower upgrades should take time? progress bar. they currently are unclear if that function is working.

**Comment by patrickdenglerhobbisoft** [comment]
I'm going to kill off the tower health because I haven't coded it anyway.  Double check I did this then close if I did.
