### ISSUE TITLE
Enter location?

### ISSUE THREAD

**Issue by Xerenn** [patrickdenglerhobbisoft/WorldDefense#89]
Not 100% sure on this. but on my first two runs, i hadnt entered the windows request of a default location. Possible result on white house defense was i wasnt given a phone booth? either way didnt have one the first two times i tried now i seem to have one. and have since put in the location.

**Comment by patrickdenglerhobbisoft** [comment]
Sorry, try again to explain :)
1. I entered blah
2. I clicked blah
